# 服务端口
server:
  port: 8083

# jdbc配置
spring:
  # dubbo 配置
  dubbo:
    # dubbo 服务名称
    application: manage-web
    # dubbo 服务扫描路径
    base-package: com.nbchen.gmall
    # dubbo 通讯协议的名称
    protocol:
      name: dubbo
    registry:
      # zookeeper 注册中心的名称
      address: 192.168.17.146:2181
      # zookeeper 通讯协议的名称
      protocol: zookeeper
    consumer:
      timeout: 600000  # 是访问提供端服务的超时时间，默认是1000毫秒
      check: false # 是启动消费端时，是否检查服务端能否正常访问。如果选择true，那启动消费端时，必须保证提供端服务正常，否则接口无法注入。

# 日志级别
logging:
  level:
    com.nbchen.gmall: debug  # 自定义路径下的日志级别


