
# \u670D\u52A1\u7AEF\u53E3
server:
  port: 8081

spring:
  # dubbo \u914D\u7F6E
  dubbo:
    # dubbo \u670D\u52A1\u540D\u79F0
    application: user-web
    # dubbo \u670D\u52A1\u626B\u63CF\u8DEF\u5F84
    base-package: com.nbchen.gmall
    # dubbo \u901A\u8BAF\u534F\u8BAE\u7684\u540D\u79F0
    protocol:
      name: dubbo
    registry:
      # zookeeper \u6CE8\u518C\u4E2D\u5FC3\u7684\u540D\u79F0
      address: 192.168.17.146:2181
      # zookeeper \u901A\u8BAF\u534F\u8BAE\u7684\u540D\u79F0
      protocol: zookeeper
    consumer:
      # \u8BBE\u7F6E\u8D85\u65F6\u65F6\u95F4
      timeout: 600000
      # \u8BBE\u7F6E\u662F\u5426\u68C0\u67E5\u670D\u52A1\u5B58\u5728
      check: false

# \u65E5\u5FD7\u7EA7\u522B
logging:
  level:
    com.nbchen.gmall.*: debug  # \u81EA\u5B9A\u4E49\u8DEF\u5F84\u4E0B\u7684\u65E5\u5FD7\u7EA7\u522B